name: tatiana samoylova
favicon: null
layout_spectrum: 0.4201089860871434
typography_spectrum: 0.6551231695339084
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010005'
    - '#eaf1f7'
    - '#4b6270'
    - '#a8bfcf'
    - '#6a7c8a'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
